name: ReRouteoptions:
  bundleIdPrefix: com.sunkeynar
  deploymentTarget:
    macOS: "13.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
targets:
  ReRoute:    type: application
    platform: macOS
    sources:
      - path: Sources
    resources:
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sunkeynar.reroute
        INFOPLIST_FILE: Resources/Info.plist
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        # App runs as a menu bar agent (no Dock icon)
        OTHER_SWIFT_FLAGS: ["-D", "MENUBAR_AGENT"]
